name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        tools: phpstan, php-cs-fixer
        coverage: none

    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-interaction --no-progress

    - name: Check PHP Syntax Errors
      run: find . -type f -name '*.php' -not -path './vendor/*' -exec php -l {} \; > /dev/null

    - name: Run PHPStan (if configured)
      run: |
        if [ -f phpstan.neon ]; then
          ./vendor/bin/phpstan analyse || echo "PHPStan not configured, skipping..."
        else
          echo "PHPStan not configured, skipping..."
        fi

    - name: Check Code Style (Pint)
      run: |
        if [ -f vendor/bin/pint ]; then
          ./vendor/bin/pint --test || echo "Pint check completed with warnings"
        else
          echo "Pint not installed, skipping..."
        fi

    - name: Security Check
      run: |
        composer audit || echo "Security audit completed"

    - name: Check for Environment File
      run: |
        if [ ! -f .env.example ]; then
          echo "❌ .env.example file is missing!"
          exit 1
        fi
        echo "✅ .env.example file exists"

    - name: Notify Success
      if: success()
      run: echo "✅ Code quality checks passed!"
